<?php

/**
 * This file is part of the package magicsunday/webtrees-fan-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 *
 * This file was updated by herr--rossi (hr).
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use HerrRossi\Webtrees\DescendantFanChart\Configuration;

/**
 * @var array         $id               The unique chart ID
 * @var Configuration $configuration
 * @var string        $title
 * @var string        $moduleName
 * @var Individual    $individual
 * @var Individual    $individualDL1
 * @var Individual    $individualDL2
 * @var Tree          $tree
 * @var array         $chartParams
 * @var string        $javascript
 * @var string[]      $stylesheets
 * @var string[]      $exportStylesheets A list of stylesheets used by SVG export
 * @var string        $ajaxUrl
 */
?>

<div class="webtrees-fan-chart">
    <h2 class="wt-page-title"><?= $title ?></h2>

    <form id="webtrees-fan-chart-form" method="post" class="wt-page-options wt-page-options-fan-chart d-print-none">
        <?= csrf_field() ?>

        <div class="row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="xref">
                <?= I18N::translate('Individual') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?=
                    view('components/select-individual', [
                        'name'       => 'xref',
                        'individual' => $individual,
                        'tree'       => $tree,
                        'required'   => true,
                    ])
                ?>
            </div>
        </div>

        <?= view($moduleName . '::modules/fan-chart/form/generations', ['configuration' => $configuration]) ?>

        <div class="collapse" id="showMoreOptions">
        <?= view($moduleName . '::modules/fan-chart/form/options', ['configuration' => $configuration, 'tree' => $tree, 'individualDL1' => $individualDL1, 'individualDL2' => $individualDL2,]) ?>
        </div>

        <div class="row mt-3">
            <div class="col-sm-12 wt-page-options-value text-center">
                <div class="btn-toolbar justify-content-between">
                    <div class="btn-group btn-group-sm">
                        <input class="btn btn-primary" type="submit" value="<?= I18N::translate('View') ?>">
                    </div>
                            
                    <div class="btn-group btn-group-sm">
                        <button id="options"
                                class="btn btn-primary"
                                type="button"
                                data-bs-toggle="collapse"
                                data-bs-target="#showMoreOptions"
                                aria-expanded="false"
                                aria-controls="showMoreOptions">
                            <span><?= I18N::translate('Show more options') ?></span>
                            <span class="d-none"><?= I18N::translate('Hide more options') ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div class="row webtrees-fan-fullscreen-container">
        <?= view($moduleName . '::modules/components/buttonbar', ['configuration' => $configuration, 'moduleName' => $moduleName]) ?>
        <div id="webtrees-fan-chart-container-<?= $id ?>" class="webtrees-fan-chart-container wt-ajax-load wt-page-content wt-chart wt-fan-chart"></div>
    </div>
</div>

<?php View::push('styles') ?>
    <?php foreach ($stylesheets as $stylesheet) : ?>
        <link rel="stylesheet" href="<?= e($stylesheet) ?>">
    <?php endforeach ?>
<?php View::endpush(); ?>

<?php View::push('javascript'); ?>
<script src="<?= e($javascript) ?>"></script>
<script>

/**
 * Load chart data and draws the chart.
 *
 * @param {FanChart} fanChart
 * @param {string}   dataUrl
 */
function drawChart(fanChart, dataUrl)
{
    // Create URL
    let url = new URL(dataUrl);
    url.searchParams.set("xref", document.getElementById("xref").value);
    url.searchParams.set("generations", fanChart.configuration.generations);
    url.searchParams.set("xrefDL1", document.getElementById("xrefDL1").value);
    url.searchParams.set("xrefDL2", document.getElementById("xrefDL2").value);
    url.searchParams.set("descendantsOptions", $('input[name=descendantsOptions]:checked').val());

    // Fetch data
    fetch(
        url.toString(),
        {
            headers: {
                "Content-Type": "application/json",
            }
        }
    ).then(
        response => response.json()
    ).then(
        data => fanChart.draw(data.data)
    ).catch(
        error => console.error(error)
    );
}

/**
 * Set visibility of "Show more options" to previous state after page reload.
 * Toggle text on "Show more options" on click.
 *
 * @param {Storage} storage
 */
function toggleMoreOptions(storage)
{
    // Options container
    const showMoreOptions = document.getElementById('showMoreOptions');

    // Options toggle button
    const optionsToggle = document.getElementById('options');

    showMoreOptions.addEventListener('shown.bs.collapse', () => {
        storage.write("showMoreOptions", true);
    });

    showMoreOptions.addEventListener('hidden.bs.collapse', () => {
        storage.write("showMoreOptions", false);
    });

    optionsToggle.addEventListener('click', () => {
        Array.from(optionsToggle.children).forEach((element, index) => {
            element.classList.toggle('d-none');
        });
    });

    if (storage.read("showMoreOptions")) {
        optionsToggle.click()
    }
}

// Set up storage object
const storage = new WebtreesFanChart.Storage("webtrees-descendant-fan-chart");

// Register all form elements valid for storing data

storage.register("generations");
storage.register("highlightDeceasedYoung");
//storage.register("xrefDL1"); // not working
//storage.register("xrefDL2"); // not working

// Handle option toggle button
toggleMoreOptions(storage);


let data     = <?= $chartParams ?>;
let ajaxUrl  = <?= json_encode($ajaxUrl) ?>;
let cssFiles = <?= json_encode($exportStylesheets) ?>;

// Create chart instance with stored configuration
const fanChart = new WebtreesFanChart.FanChart(
    "#webtrees-fan-chart-container-<?= $id ?>",
    {
        labels: data.labels,
        generations: parseInt(storage.read("generations")),
        highlightDeceasedYoung: storage.read("highlightDeceasedYoung"),
        showImages: data.showImages,
        showSilhouettes: data.showSilhouettes,
        rtl: data.rtl,
        cssFiles: cssFiles
    }
);

// Load initial chart data
drawChart(fanChart, ajaxUrl);

</script>
<?php View::endpush(); ?>
